### ISSUE TITLE
Feature Request: comments only

### ISSUE THREAD

**Issue by hoffoo** [whatyouhide/vim-lengthmatters#12]
Would it be difficult to add some kind of prefix (say  // or #) for the highlighting to apply to? Would be nice to have an override to only apply only for comments.

Thanks for a cool plugin!

**Comment by whatyouhide** [comment]
Closing this as, as it can be easily seen :smile:, I'm not working on this plugin anymore (I even use Emacs now :confused:). If anyone's up for it, please go ahead! :heart_decoration:

**Comment by ELLIOTTCABLE** [comment]
@whatyouhide — it's no biggie to have open issues on an old, unmaintained repo! If anything, that encourages people to consider offering to take over maintenance.

In that spirit, I think this Issue should be left open … even if you, personally, won't likely ever get to it. (And that's totally okay!) `<3`
