### ISSUE TITLE
disable for term:// buffers

### ISSUE THREAD

**Issue by bmedicke** [whatyouhide/vim-lengthmatters#13]
Neovim introduced the ability to open a terminal in a buffer via `:terminal`. It would be useful to disable lengthmatters for them by default. They don't set a filetype but the buffer names always start with `term://`.

https://github.com/neovim/neovim/blob/master/runtime/doc/nvim_terminal_emulator.txt#L44

**Comment by whatyouhide** [comment]
Just pushed an update which should solve this by disabling the plugin for buffers which have a `&buftype` of `"terminal"`. Let me know if it works :).

**Comment by bmedicke** [comment]
Strange, that does not work. Opening a terminal buffer and executing `:set buftype?` does return `buftype=terminal` though. Calling `LengthmattersReload` disables the plugin just fine. Maybe the `buftype` is set after your check.

**Comment by luizribeiro** [comment]
Same here. I think we should be adding an `autocmd` for `TermOpen` instead of reading the `&buftype`, as `&buftype` may not be set at the time that we're checking for it.

I tried adding this on my `.nvimrc` and it seemed to work:

```viml
  autocmd! TermOpen * LengthmattersDisable 
```

**Comment by whatyouhide** [comment]
@luizribeiro would you be willing to make a PR for this? :)

**Comment by oblitum** [comment]
> Strange, that does not work. Opening a terminal buffer and executing :set buftype? does return buftype=terminal though. Calling LengthmattersReload disables the plugin just fine. Maybe the buftype is set after your check.

This could have something to do with #14, which has been closed. Please try your issue again to check whether it's still happening.

**Comment by oblitum** [comment]
Ah. I guess the fix applied on 475d404c to exclude terminal filetypes probably won't benefit from the resolution on #14 because the exclusion check was made from outside the exclusion list in a hardcoded manner.

@whatyouhide Why not just add terminal to the excluded list?

**Comment by oblitum** [comment]
I'm just speculating though, I didn't check whether excluding terminal types the current way will still benefit from #14.

**Comment by oblitum** [comment]
If you check #14 is not helping with the current exclusion method for terminal, you may try putting something like this configuration on your `.vimrc` to see whether it works:

```vim
" lengthmatters Setup {{{
let g:lengthmatters_match_name = 'Visual'
let g:lengthmatters_excluded = [
    \ '', 'qf', 'help', 'terminal', 'unite', 'tagbar', 'gundo', 'vimshell', 'vimfiler',
    \ 'quickrun', 'python', 'html', 'javascript', 'css', 'scss', 'latex',
    \ 'haskell', 'purescript', 'elm'
    \ ]
" }}}
```

**Comment by oblitum** [comment]
You know, I guess I'll make #14 more consistent with 475d404 and use `s:ShouldBeDisabled()`, which I didn't. I guess this will then fix this too. Once consistent, this issue will probably be fixed for sure, you then may option to let `'terminal'` check hardcoded as it is, or put in the default exclusion list as I've commented.
