### ISSUE TITLE
Useful configuration vars are not documented

### ISSUE THREAD

**Issue by oblitum** [whatyouhide/vim-lengthmatters#18]
There are some useful configuration variables that are not present in README.md or Vim docs. They should be added.

Maybe I'll do a pull request in later time but if you or anyone is willing to do so feel free.

**Comment by whatyouhide** [comment]
Yes @oblitum, a PR would be greatly appreciated :) 💟

**Comment by whatyouhide** [comment]
Ping @oblitum?

**Comment by oblitum** [comment]
I don't recall which vars I was referring to and revising it now, it seems all that should be documented is already. Other vars left undocumented are just for internal use as far as I see. At the time I used then I guess, but then noticed that I should be using `lengthmatters#highlight`, etc, instead, for example.
