### ISSUE TITLE
Support for gitmessage subjects, and similar situations

### ISSUE THREAD

**Issue by ELLIOTTCABLE** [whatyouhide/vim-lengthmatters#20]
So, I don't even know what the ideal interface for configuring this would look like (a mapping of line-number to special rule? And how does the user limit it by filetype?); but I'd really like to see support for git-commit-message-style rules:

“Line 1 should be under 50 characters, line 2 should be 0 characters, and the rest of the file should be under 72 characters.”

(I understand this project is unmaintained, but perhaps somebody with more time than myself will come along and consider this worth implementing. `¯\_(ツ)_/¯`)

**Comment by whatyouhide** [comment]
@ELLIOTTCABLE as you said this is unmaintained so I'll close this issue off, but if someone wants to tackle this please feel free to do it and let me know :).
