### ISSUE TITLE
different length for different filetypes

### ISSUE THREAD

**Issue by lewicki-pk** [whatyouhide/vim-lengthmatters#22]
Hi,
At first I wanted to propose that somebody add a possibility to have different line length in different filetypes but after short googleing I've found that it is possible with local textwidth.

Could you add that to the documentation?

The command I'm using is:

`autocmd bufreadpre *.java setlocal textwidth=120`

for other filetypes I use a default 80.

**Comment by whatyouhide** [comment]
Hey @lewicki-pk, thanks for letting me know. Would you mind opening a PR to add this to the documentation please? I'm swamped with work 😄

**Comment by lewicki-pk** [comment]
Sure. I get that very well :-) 
I've added a PR #23

**Comment by whatyouhide** [comment]
Closed by #23.
