### ISSUE TITLE
Showbreak character is counted in length

### ISSUE THREAD

**Issue by Huluk** [whatyouhide/vim-lengthmatters#26]
When I set a showbreak character (e.g. `set showbreak=↪`), this character is counted as part of the line, and the highlight starts at an earlier position.

**Comment by whatyouhide** [comment]
Hey @Huluk, thanks for the report! I don't have bandwidth to work on this anytime soon, any chance you could take a stab at a PR? Thanks in advance! ❤️

**Comment by Huluk** [comment]
I may well look into the issue, but probably not anytime soon either^^ At least it's documented for now and we'll see who tackles it first ;)
