### ISSUE TITLE
Breakindent causes weird interactions

### ISSUE THREAD

**Issue by Huluk** [whatyouhide/vim-lengthmatters#27]
When breakindent is enabled, highlight mostly disappears, except sometimes during window resizing.

Example configuration:
```
set breakindent
set breakindentopt=shift:4
```

**Comment by whatyouhide** [comment]
Hey @Huluk, thanks for the report! I don't have bandwidth to work on this anytime soon, any chance you could take a stab at a PR? Thanks in advance! ❤️

**Comment by Huluk** [comment]
Same as on #26 , I may look into it, but probably not right away. Thanks for the fast reply, and for maintaining lengthmatters in the first place :)
